### ISSUE TITLE
Trying to use the lavis models outside of the folder is giving me an error

### ISSUE THREAD

**Issue by EricZhao9482** [ZhaoPeiduo/BLIP2-Japanese#3]
I got everything working in the example.ipynb file. 
So I am trying to use this outside of the BLIP-Japanese-master folder in some other python file. I'm using all the import statements shown in the example.ipynb file. However I keep running into this error saying:

`    from lavis.common.registry import registry
ModuleNotFoundError: No module named 'lavis'`

I even tried using importlib to work around the directory naming issues with hyphens like this:
`    BJMLavisModels = "BLIP2-Japanese-master.lavis.models"
    ImageCaptioning = importlib.import_module(BJMLavisModels)
    print(model_zoo)`

but i still get the no module named lavis error. BTW I'm running this on windows instead of a UNIX system currently.

**Comment by ZhaoPeiduo** [comment]
Hi Eric,

You may consider the following code block for your particular case:
```
import sys

sys.path.append('./BLIP2-Japanese') # TODO: Edit your project path accordingly

from lavis.common.registry import registry # Should work
```

Apologies for not being able to do a proper packaging for this project (and I do not think this will be done if the project is not receiving further attention -- it is experimental after all). If the above walk-around does not work, you may consider visiting stackoverflow or use chatgpt to resolve your issue :)

best

**Comment by EricZhao9482** [comment]
That resolved it thanks!
