### ISSUE TITLE
About the ITC Loss on Qformer-pretrain

### ISSUE THREAD

**Issue by pty12345** [ZhaoPeiduo/BLIP2-Japanese#5]
Hi, I have a question about the ITC(Image-Text-Contrastive Learning) loss:

On https://github.com/ZhaoPeiduo/BLIP2-Japanese/blob/master/lavis/models/blip2_models/blip2_qformer.py#L140: 

When calculating the similarity matrix between image and text, it seems that you divide a learnable parameter **self.temp**.
What is the purpose of it? To enlarge the value of similarity matrix?

**Comment by ZhaoPeiduo** [comment]
Hi sorry for the late reply. The implementation follows the original blip2_qformer which can be found [here](https://github.com/salesforce/LAVIS/blob/main/lavis/models/blip2_models/blip2_qformer.py)
